### ISSUE TITLE
TA wants to re-download all previously watched/deleted videos again

### ISSUE THREAD

**Issue by sethforprivacy** [bbilly1/tubearchivist#112]
This just happened after the upgrade to 0.9.0/ES 7.16.1, but as a part of troubleshooting #111, I did flush redis cache and restore a backup zip as well, so I very well may have caused this.

The only new feature/change that I can think of that could affect this is the new "delete watched videos after X days" which I did also enable after upgrading.

Regardless of what caused this, please let me know if there is any way to mark *all* old videos as watched so I don't have to re-download all of them again!

**Comment by bbilly1** [comment]
Hmm, silly, of course the deleted videos will get added again when you rescan your subscriptions. It's also fixed in the hotfix so videos will get deleted and added to the ignore list at the same time to avoid that. So click on *ignore* for the previously deleted videos that got added again to the download queue.

**Comment by sethforprivacy** [comment]
> Hmm, silly, of course the deleted videos will get added again when you rescan your subscriptions. It's also fixed in the hotfix so videos will get deleted and added to the ignore list at the same time to avoid that. So click on _ignore_ for the previously deleted videos that got added again to the download queue.

Heh, I figured that was it! Guess I'll get to clicking -- 396 videos to ignore 😅 

Thanks again for all of the hard work on this!
