### ISSUE TITLE
Native installation

### ISSUE THREAD

**Issue by Orangian** [bbilly1/tubearchivist#149]
Hi, I was wondering if it was possible to run tubearchivist native without docker? Thanks for any help!

**Comment by bbilly1** [comment]
Well define `possible`. You *could* revert the steps docker is doing: Start at the docker-compose files, install the two dependencies, make sure they are reachable, set the environment variables, then look at the Dockerfile, recreate these steps there, then go through run.sh, that's the entry point script that starts all the services and follow the steps there. The file [config.json](https://github.com/bbilly1/tubearchivist/blob/master/tubearchivist/home/config.json) is doing a lot of heavy lifting there for initial startup variables. And then check for any changes after any new release.

But I'm sure, pretty quickly you'll realize the blessing Docker brings into that whole process once there are a few moving parts. One reproducible build file instead of all these single easy to mess up steps...

So, possible *yes*, absolutely, it's all open source, you can see everything that's happening. Useful? Maybe as an exercise to learn the inner workings of Docker? But beyond that, probably not much else.

That's not something I'm going to be able to help you with.

**Comment by Orangian** [comment]
Ah, thanks! Was thinking something along reading the files, just didn't know where to start. Thanks for helping!
