### ISSUE TITLE
Video release time differs from youtube, messing up order of "numbered" videos.

### ISSUE THREAD

**Issue by hugalafutro** [bbilly1/tubearchivist#193]
The order of videos in TA differs from order of when the videos were released on youtube.

I only noticed this recently, but it wasn't happening before as if I scroll back a bit the videos are in order again, so maybe something in last release? Sorry not a programmer to be able to see what causes this.

this is the same channel in TA and youtube (TA has those sans compilations and shorts.)
![image](https://user-images.githubusercontent.com/30209689/159000222-ad6d4f81-a560-41f6-8175-c12c4e3ad379.png)

At the end of the day it's just cosmetic, but if there is an easy way, I would love to have the videos in order.

Many thanks for all your work on this awesome project regardless, I have been looking for something like this for a long time!

**Comment by bbilly1** [comment]
So the issue here is that yt-dlp only returns the published date as a date like YYYYMMDD and not as a timestamp, so I assume that youtube stores the exact time and can then sort by that internally without ever displaying that. 

In your case a solution could be to sort by the title as a secondary key after the date published. Then as long as the uploader doesn't mix the dates out of order, this would work fine.

**Comment by bbilly1** [comment]
This hasn't changed since the beginning of the project. You'll only see it of an uploader adds multiple videos per day and then only in some cases. As the date published is not unique, Elasticsearch will fall back to the date edited of the document in the index, so that's probably why you see some videos sorting ok, and some not. 

Ah and btw, the 7:01 is the duration of the video and not the time. Is that not obvious? These things can sometimes be only obvious for me alone... :-)

It makes sense that this will be correct when by sorting by date downloaded, because how the videos are getting added to the download queue is sorted by date already, and this is also the download order. 

So I think sorting by title as a secondary sort option would be a good solution anyway. I've just checked a few tutorial series of mine, where they have a title like "tutorial project - 1/1" or similar, and in some cases this is out of order too. Though I usually look at the playlist which is sorted by how ever the uploader sorts the playlist, usually correct.

**Comment by hugalafutro** [comment]
Oh, you're right that's the duration :D I got confused as all the videos are so short the durations make sense as timestamp too. I guess I'm too used to see the video duration in lower right corner of the thumbnail from youtube. Although it's hard not to see it now that you mentioned it.

The channel steadily releases more per day so it probably reached the point where it throws the sorting off.

I didn't even think about the playlists, good suggestion!

**Comment by bbilly1** [comment]
this is now merged in v0.1.3 and should fix this inconsistency. please update.
