### ISSUE TITLE
v0.0.4 broke the download queue.

### ISSUE THREAD

**Issue by pairofcrocs** [bbilly1/tubearchivist#34]
After updating from v0.0.3 to v0.0.4, I can no longer add videos to my download queue. When I click "Download now" the page hangs for a second and refreshes, with the same video still available to download and the download queue is empty.

These are the logs I'm getting: https://pastebin.com/w3q3fNbV

It refers to "192.168.1.4" quite often, which confuses me, becuse the IP that all 3 services use is "192.168.1.16"

I'm running unraid to host TubeArchivist, ElasticSearch, and Redis.

**Comment by bbilly1** [comment]
The downside of the dynamic download queue is, that there can only be one queue now otherwise if there are multiple downloads going in parallel, things interfere with each other. 
That's why you see "Download queue already running." in the output there. Are you sure it's not downloading? When you refresh the download page, does it show up?

Just as a "hotfix" I have updated the current version with a quick solution to make sure that there are no leftovers when restarting the container. So pull the image again and restart. Then I'll have to look into a more permanent solution...

The 192.168.1.4 must be the IP of your docker host machine. So you can see the successful HTTP requests coming in there, indicated by the 200 status message _(HTTP/1.1 200)_.

**Comment by pairofcrocs** [comment]
That seemed to fix it!

It could have been a stuck download that was messing everything up.

As for the 192.168.1.4, it was actually my desktop that I use to access the webui of the container, that makes sense because that's where to requests would be coming from.
