### ISSUE TITLE
Any way to get nfo files for Emby/Plex Metadata?

### ISSUE THREAD

**Issue by geekedtv** [bbilly1/tubearchivist#50]
My main goal is to get the embedded thumbnails to display in Emby. I've come to realize this can't be done without an nfo file? I'm not sure if this can be done or not with tubearchivist. Can it create nfo files for metadata? FYI I do have the embedded metadata option enabled in settings.

**Comment by bbilly1** [comment]
I have given this some thought: Having Tube Archivist as a dedicated media server to download, index and stream YouTube videos to then just export and import and index it again into another media server feels like it defeats the purpose and you'd be better off to extend one of the existing downloader solutions instead. This way you wouldn't end up with the unneeded overhead of two media servers and two indexes that do the same thing and the dependency issues that's involved with that.

Put hey, this is opensource! If you or somebody wants to work on that and maintain it as part of Tube Archivist - no heart feelings! Let's keep this issue open and if there is enough interest from people who want to contribute towards that, I'll move it to a discussion and we can see what's needed to make this work.

**Comment by geekedtv** [comment]
Well, there's server side downloading and there's also media playback. I can't just pop on my tv, load up tubearchivist and let my kids watch videos from it. You see what I mean? My kids are 6 and younger. The purpose is to make the media as convenient to watch as possible. I can't sit my kids in front of a computer and let them go at it. No way lol.

**Comment by bbilly1** [comment]
I use it a lot on my android tablet, just opening the interface with Firefox, that works quite well. That would also be an easy bookmark on the home screen for your kids to click on. I don't have any experience in the smart TV ecosystem, so I don't know how many steps that would make or if there is any bookmarks possible, or how convenient a smart TV in general is. I guess that varies a lot between brands and models too, so no, that's not something I'll be able to help you with.

Please consider the circumstances: This is a one month old project on v0.0.5. I'm one guy developing that in my free time and publishing it as free software for everybody to use. I'm sorry to hear that this project doesn't fit your specific usecase perfectly but I need to focus the scope of the project on _something_, otherwise I won't get _anything_ done if I'm trying to do it all at the same time. 

But my comment above still stands: More people will come along, if you want to contribute towards that, please let me know!

**Comment by geekedtv** [comment]
Oh, I know. I really appreciate what you're doing here. In fact so much that I donated $50 the other day. I don't expect anything from that nor do I expect you to create a solution for this issue. Thank you for all you've done!

**Comment by yellowspaced** [comment]
I know this old but wanted to toss out I had the same use case, kids watching on a tv via emby. This is the best app i have found for making it easy to manage the downloads etc... i created a very bad python script to pull the metadata and tumbnail so emby can use it. might be useful to others. https://github.com/yellowspaced/tubearchivist-metadata-export/
