### ISSUE TITLE
[Feature Request] (simple) UI Improvements

### ISSUE THREAD

**Issue by TheOneValen** [bbilly1/tubearchivist#81]
Hi

I identified a few UI issues that would probably not be much effort to fix but (might) improve the user experience:

- Channel Overview: "Unsubscribe" Button is provided, but maybe also provide a "Subscribe" Button for unsubscribed channels
- Channel View: Provide a Link to the original channel (maybe folded?)
- Video View: Provide a link to the original video (maybe folded?)
- Video View: Always unfold description (don't fold it)

Greetings
Valen

**Comment by bbilly1** [comment]
Yes, sounds all good, except for showing the video description by default I'm not so sure if that is a good idea. I found the value of these varies quite a lot, sometime it's just sponsor info, sometimes it's timestamps and sometimes it's something like show notes. And mostly the length varies a lot from a line or two to scrolling through the whole height of the screen. That's why I landed on the collapsed by default for both the video and channel description.

I was thinking once the playlist situation is figured out, having a little preview of the next / previous video could be nice, could also be something like "related", or the next / previous in the channel, so more like a navigation. I think that would be a more interesting use of the space there? And if you want to open the description, it's just a click away...

I don't have a fixed opinion on any of this, what do you think?

**Comment by TheOneValen** [comment]
Yes you are right. I unfolded some descriptions and immediately wanted to fold them again. Maybe in the future users can set this as (user scoped) preference for themselves?

A "related" and next/previous would be great, but I think it can get very complicated. This is where youtube puts most of its effort. I would like to suggest a tagging system in another issue or in the discussion (soon). Maybe something like this can also be used for your next/prev idea.

**Comment by bbilly1** [comment]
OK, this is now merged in v0.0.8. Thank you for input!
