### ISSUE TITLE
[BUG][DOCKER] Changing TA_PASSWORD on docker compose should update the user password

### ISSUE THREAD

**Issue by stefanorossiti** [bbilly1/tubearchivist#82]
Took me some time to figure out why I couldn't log in after updating the container with the user system update. 
It turned out that the password set to TA_PASSWORD, which work the first time, once changed doesn't replace the user's old password with the newer. I think it should do it because that's the expected behavior once you change that environment variable.

**Comment by bbilly1** [comment]
Yes, I observed the same, that's why I was trying to specify the behavior with [create the initial credentials](https://github.com/bbilly1/tubearchivist#tube-archivist) and then again in the users section of the [wiki](https://github.com/bbilly1/tubearchivist/wiki/Users).

I think it's not ideal either way: If the environment variable overwrites the password, then if you change it in the admin interface, you will reset it again with the environment variables once you restart the container, so both is a bit unexpected.

That's why I thought the behavior makes the most sense to create the first user with the environment variables, then everything else you can change in the admin interface. That's also the default behavior of Django. 

Alternatively I also thought to have something like a first user registration form if there isn't any user set, then this would define username and password instead with the environment variables. But that sounds a bit like overengineering a simple problem that has already a builtin solution. I'm a bit torn between if it's a bug or a feature. :-)

**Comment by stefanorossiti** [comment]
Yeah, I get your point… that doesn't sound ideal either way. Especially if you have something like watchtower that automatically update your docker's images.
Well, actually if you use the docker compose, that isn't applied at the container restart but only when a docker compose down/up is done, and so would be the password update, but this would be very annoying indeed.

So maybe I wouldn't speak about overengineering, if that solution would increase user's experience and doesn't require looking at the documentation. It doesn't sound so bad to have a predefined superuser and, at first run, provide the user a link to the user's administration panel to edit the superuser account if he wants. 

But yes, overall this solution if fine too.
