### ISSUE TITLE
Is there anyway to delete the download queue?

### ISSUE THREAD

**Issue by deanpribetic** [bbilly1/tubearchivist#85]
Pretty much as described. I don't want to manually ignore everything in there…just want to delete everything In the queue, but not anything that isn't already downloaded

**Comment by bbilly1** [comment]
Hmm, no not really, at least nothing short of deleting the index, haven't thought of that...

I assume that's what you mean?
> but not anything that *is* already downloaded  

Otherwise you might have to clarify for me.

So to do that jump into the container with
```bash
docker exec -it tubearchivist bash
```
Then from within the container, assuming you haven't changed the username of elasticsearch from the default *elastic*, run
```bash
curl -XDELETE $ES_URL/ta_download -u elastic:$ELASTIC_PASSWORD
```
This will delete everything in the download queue, pending for downloading as well as previously ignored, but won't touch any of your already downloaded and indexed videos. 

Then restart the container to trigger a rebuild of the index to get a blank download queue.

That could be a useful button tho have somewhere...

**Comment by deanpribetic** [comment]
Perfect! That was exactly what I was looking for. Thank you!

**Comment by bbilly1** [comment]
OK, this is now implemented in v0.0.8. Thank you for your input!

**Comment by marcuma** [comment]
Did that button get removed? I'm on version 0.4.4 and don't see it.

**Comment by bbilly1** [comment]
https://docs.tubearchivist.com/settings/actions/#delete-download-queue
