### ISSUE TITLE
YT-DLP Output not following rule structure

### ISSUE THREAD

**Issue by MadsMighty** [bbilly1/tubearchivist#88]
I understand that renaming files is a known limitation, however I was curious why it was that YT-DLP documentation and instructions for the output template are linked in this project when it doesn't accept those commands to format the file name.

My intention is to get all of my Youtube subscriptions into Plex using the youtube metadata agent, which requires the channel ID in the channel folder name, as well as the video id in the video file name. I understand that the metadata is being embedded directly into the file however Plex can't read that information.

Would it be possible for Tube Archivist to accept the full YT-DLP output functionality? Here is the output template I'm working with:

`%(channel)s - [%(channel_id)s]/%(title)s - %(upload_date)s - %(season_id)s - [%(id)s].%(ext)s`

As an example of another open source project that accepts the above code fully, here is MeTube: 
https://github.com/alexta69/metube

Tube Archivist is perfect in almost every other way, and adding this small change would make the project PERFECT for so many with a similar workflow (anyone using Plex and Youtube). I've yet to find another PVR style app that is as slick as Tube Archivist but this is the only thing stopping me

**Comment by bbilly1** [comment]
I think you are mixing up two different things:
1. [Output template](https://github.com/yt-dlp/yt-dlp#output-template): e.g. filename template of the media file.
2. [Format selection](https://github.com/yt-dlp/yt-dlp#format-selection): e.g. stream selection like resolution, codec and more.

What you are talking about is the output template, that's currently not configurable, the format selection is. 

I'm sure you have seen the multiple previous threads going into the same direction? Like #74, #50, #38, #1 [here](https://github.com/bbilly1/tubearchivist/issues/1#issuecomment-936874874). So my answer there stands:
- Yes, it's know, yes it's a design flaw, yes it's fixable and yes I want to fix it at some point but
- No, it's not required to accomplish the [core functionality](https://github.com/bbilly1/tubearchivist#core-functionality) and no, it's not required for the [problem this project is trying to solve](https://github.com/bbilly1/tubearchivist#problem-tube-archivist-tries-to-solve) and no, it's not a small change due to the mentioned design flaw and some more issues mentioned in the threads linked above.
