### ISSUE TITLE
Feature Request: Allow to browse channel's full video list, not bound to 'recent' video page size limit

### ISSUE THREAD

**Issue by PiotrKrzyzek** [bbilly1/tubearchivist#92]
TubeArchivist works very well, though the user experience for looking through a channel's videos (once you hare subscribed to it) seems be in a good place for improvement where users would be allowed to look through the whole channels library, and not just recent items.

There are a few pieces to this so I'll try to describe things in order and neatly separated as well as a I can.

**What Currently Happens:**
When a user subscribes to a channel, in use case let's say Critical Role as they plenty of videos to describe this use case, they are able to see, after indexing, the latest X videos where X is the number set in Settings -> Application Settings -> Subscriptions -> Current Page Size Input Box (defaults to 50).

Thus, the user will only be able to see this channels 50 latest videos and no more.

If a user clicks the Rescan Subscriptions button on the Downloads page, the system will scan and see the same set of latest videos and do nothing (because there are no new videos).

**Expected Behavior:**
We have several options for this: (a) clicking rescan, if finding no new videos scans backwards in time (finding older videos instead of newer ones), (b) add a scan backwards button, (c) add a scan full channel button, (d) add a feature (and option in settings) to fully scan the full channel for videos upon initial subscription to channel (default: false) in addition to one of the options of a, b, or c.

(A) Clicking rescan is able to scan both for newest videos, and for older videos:

Currently, the rescan button only scans for newer videos from the latest videos gotten or last scan time (or whatever. It would be nifty that if it can't find new videos, or it find some but not enough to cross the new scan limit (currently defaults to 50): it would then start scanning backwards from the currently oldest known video.

This would allow a user a keep on smashing that button in-order to keep on indexing older and older videos.

(B) Adding a Scan Backwards In Time button:
The rescan button scans for newer videos, so why not add a feature/button to scan for older videos!

This would allow a user to keep on scaning, up to the 50 size limit, exactly the same as the current scan button ... but in the opposite direction.

(C) Full channel scan button
The current scanning / rescan functionality only searches for new videos up to the page size limit. What if a user wants the whole and complete channel index (or re-indexed)?

Offering them a "scan the whole darn thing, bandwidth be damned" sounds like a wonderful way to at a minimum index a whole channel and thus offer an easy way to users to get everything all in one place.

(D) Full Scan At Subscription
When a channel is added to (Subscribed to) in TubeArchivist, it runs through an initial scan up to the page size limit. What if there were an option/setting that for any new channel added, it could scan (index) the whole thing? That would be neat.

This feature can then be combined with any of the above to allow for re-indexing or looking for additional items.

This 'full scan' should have no limit and should continue until done or errors out. Probably a good idea to include a stop scan / cancel scan button in there somewhere 'just in case'.

**Comment by bbilly1** [comment]
Thanks for your comment. A few things first, just to make sure we are talking about the same thing:

1. There is the [Archive View page size](https://github.com/bbilly1/tubearchivist/wiki/Settings#archive-view) that defines how many videos / channels / playlists show in the interface on a given page, if you have more videos than that in the current view, you can get to the next page at the bottom using pagination and you also have some more sorting option at the top there too. That's purely about how many videos you want to load in a given page and has nothing to do with the download functionality.
2. Then there is the [subscriptions page size](https://github.com/bbilly1/tubearchivist/wiki/Settings#subscriptions) that defines how far the "rescan" will search for. That's a feature of yt-dlp, the command line equivalent is `--playlist-end`. yt-dlp extracts 50 videos per page, hence it makes sense to use the same size.

Then the whole purpose of the *Rescan Subscriptions* is to find new videos, so as long as you rescan sooner than your subscribed channel publishes 50 videos you will stay up to date. There won't be any *new* videos further back. Setting a bigger size than 50 to rescan maybe daily will result in a lot of useless traffic to YouTube.

But you can add anything with the "Add to download queue" form, whole channel, playlist, or just a list of links, as described [here](https://github.com/bbilly1/tubearchivist/wiki/Downloads#add-to-download-queue). So for example you want to subscribe to a channel but you can still download all of the videos available first then because you are subscribed, you can find new videos by rescanning. 

So with that,
- For (A) and (B), this could be something on the channel page, have a text input form to search for x more videos to add to the download queue from that channel. Not sure if that's the best place though. Could also be a more sophisticated *add to download queue* form with filters by date or by how many videos to add, but that will get complicated and potentially confusing fast. That's some thing to think about if and how this could be done.
- Then (C) and (D) are already implemented, as you can download the whole channel at once, as described above.

**Comment by PiotrKrzyzek** [comment]
Since these settings / features seem to be there already ... I think what I would like to see is an improved user experience on being able to do the above.

I don't have any direct suggestions for that at the moment other than potentially an easy access button (or something) for: "archive whole channel / playlist regardless of page size setting" and/or "process older videos" (which would pull the X number of videos by page size by date backwards, instead of newer).

I'll think on this a bit more and I hope I can present some visuals and better written explanations soon. :)

**Comment by bbilly1** [comment]
Closing this one for now, feel free to reword and open a separate issue.
